on: push
name: My cool Action
job:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Go Modules
      uses: cedrickring/golang-action/go1.12@1.3.0
      env:
        GO111MODULE: "on"
